const List<String> allergenNames = [
  'Alcohol',
  'Celery',
  'Chilli',
  'Dairy',
  'Egg',
  'Fish',
  'Gelatin',
  'Gluten',
  'Lupin',
  'Mustard',
  'Peanuts',
  'Sesame',
  'Shellfish',
  'Soy',
  'Sulphites',
  'Tree Nuts',
];

const List<String> preferenceNames = [
  'Salty',
  'Sweet',
  'Bitter',
  'Sour',
  'Crunchy',
  'Chewy',
  'Smooth',
  'Creamy',
  'Wet',
  'Dry',
  'Cold',
  'Spicy',
  'Savoury',
  'Textured',
  'Soft',
  'Mild',
  'Rich',
];

const List<String> preferenceExamples = [
  'Examples: Chips, Pretzels, Olives',
  'Examples: Chocolate, Candy, Fruit',
  'Examples: Coffee, Dark Chocolate, Grapefruit',
  'Examples: Lemon, Vinegar, Tamarind',
  'Examples: Chips, Crackers, Carrots',
  'Examples: Gummy Candy, Chewy Meat, Caramel',
  'Examples: Yogurt, Custard, Smoothies',
  'Examples: Mashed Potatoes, Ice Cream, Butter',
  'Examples: Soup, Stew, Sauces',
  'Examples: Crackers, Toast, Rice Cakes',
  'Examples: Ice Cream, Popsicles, Cold Drinks',
  'Examples: Hot Sauce, Chili, Spicy Snacks',
  'Examples: Soy Sauce, Parmesan, Bouillon',
  'Examples: Raw Vegetables, Tofu, Bread Crumbs',
  'Examples: Bread, Cake, Marshmallows',
  'Examples: Mild Cheese, Vanilla, Oatmeal',
  'Examples: Dark Chocolate, Cheese, Nuts',
];

const List<String> dayNames = [
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
  'Sunday',
];